# Generated by Django 5.0.3 on 2024-03-25 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0003_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300)),
                ('score', models.IntegerField()),
                ('is_correct', models.BooleanField(default=False)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResultIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.CharField(max_length=300)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('correct_answer', models.TextField()),
                ('result_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sim.resultrecord')),
            ],
        ),
    ]
