# Generated by Django 5.0.3 on 2024-03-25 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0008_alter_resultrecord_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='resultindividual',
            name='quiz',
            field=models.CharField(max_length=250),
        ),
    ]
